// Generated by CoffeeScript 1.12.7
(function() {
  var http, port, server;

  http = require('http');

  server = http.createServer(req, res)(function() {
    res.writeHeader(200, {
      'Content-Type': 'text/plain'
    });
    res.write('Hello, World!');
    return res.end();
  });

  port = process.env.port || 1337;

  server.listen(port);

  console.log("Server running at http://localhost:%d", port);

}).call(this);
